# Generated by Django 3.2.5 on 2021-10-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MaterialModel', '0017_auto_20210813_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('avatar', models.CharField(max_length=200)),
                ('average_temperature', models.FloatField(verbose_name='平均温度')),
                ('temperature_difference', models.FloatField(verbose_name='温差，最低月平均温度与最高月平均温度之差')),
                ('average_annual_precipitation', models.FloatField(verbose_name='平均年降水量')),
                ('average_annual_precipitation_days', models.FloatField(verbose_name='平均年降水日数')),
                ('average_annual_sunshine_hours', models.FloatField(verbose_name='平均年日照时数')),
                ('climate', models.CharField(choices=[('温带季风', '温带季风'), ('亚热带季风', '亚热带季风'), ('热带季风', '热带季风'), ('地中海', '地中海'), ('温带大陆', '温带大陆'), ('温带海洋', '温带海洋')], default='温带季风', max_length=20)),
                ('weather', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('precipitation', models.CharField(max_length=20)),
                ('min_irrigation_default', models.IntegerField(verbose_name='最小灌溉值')),
                ('average_irrigation_default', models.IntegerField(verbose_name='平均灌溉值')),
                ('max_irrigation_default', models.IntegerField(verbose_name='最大灌溉值')),
                ('raw_fertility_default', models.IntegerField(verbose_name='默认肥力值')),
                ('is_flooding', models.BooleanField(verbose_name='是否会泛滥')),
                ('flooding', models.BooleanField(verbose_name='是否正在泛滥')),
                ('flooding_fertility_default', models.IntegerField(verbose_name='泛滥肥力值')),
                ('irrigation_default', models.FloatField(verbose_name='默认灌溉值')),
                ('fertility_default', models.FloatField(verbose_name='默认肥力值')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('list_of_producible_materials', models.ManyToManyField(related_name='producible_materials', to='MaterialModel.Material', verbose_name='可产物品表')),
                ('list_of_special_materials', models.ManyToManyField(related_name='special_materials', to='MaterialModel.Material', verbose_name='特产表')),
            ],
        ),
    ]
