# Generated by Django 3.2.5 on 2021-10-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0017_auto_20210813_2354'),
        ('CityModel', '0002_auto_20211013_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='气候名')),
                ('rain_chance_spring', models.FloatField(verbose_name='春天下雨概率')),
                ('rain_chance_summer', models.FloatField(verbose_name='夏天下雨概率')),
                ('rain_chance_autumn', models.FloatField(verbose_name='秋天下雨概率')),
                ('rain_chance_winter', models.FloatField(verbose_name='冬天下雨概率')),
                ('rain_season_buff_spring', models.FloatField(verbose_name='春天下雨量修正')),
                ('rain_season_buff_summer', models.FloatField(verbose_name='夏天下雨量修正')),
                ('rain_season_buff_autumn', models.FloatField(verbose_name='秋天下雨量修正')),
                ('rain_season_buff_winter', models.FloatField(verbose_name='冬天下雨量修正')),
                ('raw_rain_days', models.IntegerField(verbose_name='原始下雨天数')),
            ],
            options={
                'verbose_name': '气候',
                'verbose_name_plural': '气候',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='city_road',
            options={'verbose_name': '城与城道路', 'verbose_name_plural': '城与城道路'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': '县', 'verbose_name_plural': '县'},
        ),
        migrations.AlterModelOptions(
            name='default_open_difficulty',
            options={'verbose_name': '基准开垦难度参数', 'verbose_name_plural': '基准开垦难度参数'},
        ),
        migrations.AlterModelOptions(
            name='suburb',
            options={'verbose_name': '郊区', 'verbose_name_plural': '郊区'},
        ),
        migrations.AlterField(
            model_name='county',
            name='list_of_special_materials_county',
            field=models.ManyToManyField(blank=True, related_name='special_materials_county', to='MaterialModel.Material', verbose_name='特产表'),
        ),
        migrations.AddField(
            model_name='city',
            name='climate_table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CityModel.climate', verbose_name='气候-外键'),
            preserve_default=False,
        ),
    ]
