# Generated by Django 3.2.5 on 2021-10-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CivitasModel', '0002_auto_20211015_0043'),
        ('CityModel', '0003_auto_20211013_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='climate_table',
        ),
        migrations.AddField(
            model_name='city',
            name='calendar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CivitasModel.calendar', verbose_name='日历'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='flooding_season',
            field=models.CharField(choices=[(1, '春'), (2, '夏'), (3, '秋'), (4, '冬')], default=1, max_length=20, verbose_name='泛滥季节'),
        ),
        migrations.AddField(
            model_name='county',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suburb',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='climate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityModel.climate', verbose_name='气候'),
        ),
    ]
