# Generated by Django 3.2.5 on 2021-10-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityModel', '0005_auto_20211021_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_rain',
            field=models.BooleanField(default=1, editable=False, verbose_name='是否正在下雨'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='fertility_default',
            field=models.FloatField(verbose_name='当前默认肥力值'),
        ),
        migrations.AlterField(
            model_name='city',
            name='flooding',
            field=models.BooleanField(editable=False, verbose_name='是否正在泛滥'),
        ),
        migrations.AlterField(
            model_name='city',
            name='flooding_fertility_default',
            field=models.IntegerField(null=True, verbose_name='泛滥肥力值'),
        ),
        migrations.AlterField(
            model_name='city',
            name='flooding_season',
            field=models.CharField(choices=[('1', '春'), ('2', '夏'), ('3', '秋'), ('4', '冬')], max_length=20, null=True, verbose_name='泛滥季节'),
        ),
        migrations.AlterField(
            model_name='city',
            name='irrigation_default',
            field=models.FloatField(verbose_name='当前默认灌溉值'),
        ),
    ]
