# Generated by Django 3.2.5 on 2021-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0017_auto_20210813_2354'),
        ('CityModel', '0006_auto_20211022_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='flooding',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否正在泛滥'),
        ),
        migrations.AlterField(
            model_name='city',
            name='flooding_fertility_default',
            field=models.IntegerField(blank=True, null=True, verbose_name='泛滥肥力值'),
        ),
        migrations.AlterField(
            model_name='city',
            name='flooding_season',
            field=models.CharField(blank=True, choices=[('1', '春'), ('2', '夏'), ('3', '秋'), ('4', '冬')], max_length=20, null=True, verbose_name='泛滥季节'),
        ),
        migrations.AlterField(
            model_name='city',
            name='list_of_special_materials',
            field=models.ManyToManyField(blank=True, related_name='special_materials', to='MaterialModel.Material', verbose_name='特产表'),
        ),
    ]
