# Generated by Django 3.2.5 on 2021-11-02 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MaterialModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('type_of', models.CharField(choices=[('个人', '个人'), ('不动产', '不动产'), ('城市', '城市')], default='个人', max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name': '库房',
                'verbose_name_plural': '库房',
            },
        ),
        migrations.CreateModel(
            name='Depository_To_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='数量')),
                ('depository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depository_material', to='DepositoryModel.depository', verbose_name='库房')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material_detail', verbose_name='物资')),
            ],
            options={
                'verbose_name': '库房物资中间表',
                'verbose_name_plural': '库房物资中间表',
            },
        ),
        migrations.AddField(
            model_name='depository',
            name='depository_materials',
            field=models.ManyToManyField(related_name='depository_materials', through='DepositoryModel.Depository_To_Material', to='MaterialModel.Material_Detail', verbose_name='库房拥有物资'),
        ),
    ]
