# Generated by Django 3.2.5 on 2021-10-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MaterialModel', '0017_auto_20210813_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '不动产需求物资',
                'verbose_name_plural': '不动产需求物资',
            },
        ),
        migrations.CreateModel(
            name='Estate_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='不动产类型名')),
                ('max_lands', models.FloatField(verbose_name='占地面积')),
                ('need_material', models.ManyToManyField(through='EstateModel.Estate_Material', to='MaterialModel.MaterialDetail', verbose_name='建设需要材料')),
            ],
            options={
                'verbose_name': '不动产类型',
                'verbose_name_plural': '不动产类型',
            },
        ),
        migrations.AddField(
            model_name='estate_material',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateModel.estate_type', verbose_name='不动产'),
        ),
        migrations.AddField(
            model_name='estate_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.materialdetail', verbose_name='物资'),
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='不动产名')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateModel.estate_type', verbose_name='类型')),
            ],
            options={
                'verbose_name': '不动产',
                'verbose_name_plural': '不动产',
            },
        ),
    ]
