# Generated by Django 3.2.5 on 2021-11-02 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialModel', '0001_initial'),
        ('EstateModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_owner', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AddField(
            model_name='estate',
            name='production_machining',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.recipe', verbose_name='产出配方'),
        ),
        migrations.AddField(
            model_name='estate',
            name='production_materials',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material_detail', verbose_name='产物'),
        ),
        migrations.AddField(
            model_name='estate',
            name='type_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateModel.estate_type', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='estate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_user', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AddField(
            model_name='ab',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateModel.abc'),
        ),
    ]
