# Generated by Django 3.2.5 on 2021-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0017_auto_20210813_2354'),
        ('CivitasModel', '0003_auto_20211021_1535'),
        ('EstateModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estate_Material',
            new_name='Estate_To_Material',
        ),
        migrations.AddField(
            model_name='estate',
            name='fertility',
            field=models.FloatField(blank=True, default=1, verbose_name='肥力值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='irrigation',
            field=models.FloatField(blank=True, default=1, verbose_name='灌溉值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='now_lands',
            field=models.FloatField(default=1, verbose_name='当前占地'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='allowable_terrain',
            field=models.ManyToManyField(related_name='allow_terrain', to='CivitasModel.Terrain', verbose_name='允许建设的地形'),
        ),
        migrations.AddField(
            model_name='estate_type',
            name='best_terrain',
            field=models.ManyToManyField(related_name='best_terrain', to='CivitasModel.Terrain', verbose_name='最适地形'),
        ),
        migrations.AddField(
            model_name='estate_type',
            name='is_fertility',
            field=models.BooleanField(default=1, verbose_name='是否使用肥力值机制'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='is_house',
            field=models.BooleanField(default=1, verbose_name='是否为住宅'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='is_irrigation',
            field=models.BooleanField(default=1, verbose_name='是否使用灌溉值机制'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='is_machining',
            field=models.BooleanField(default=1, verbose_name='是否为加工建筑'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='is_raw_materials',
            field=models.BooleanField(default=1, verbose_name='是否为原材料建筑'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='is_restaurant',
            field=models.BooleanField(default=1, verbose_name='是否为餐厅'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='list_of_machining',
            field=models.ManyToManyField(blank=True, related_name='list_machining', to='MaterialModel.Recipe', verbose_name='可产加工品'),
        ),
        migrations.AddField(
            model_name='estate_type',
            name='list_of_raw_materials',
            field=models.ManyToManyField(blank=True, related_name='list_raw_materials', to='MaterialModel.MaterialDetail', verbose_name='可产原料表'),
        ),
        migrations.AddField(
            model_name='estate_type',
            name='number_of_house_person',
            field=models.IntegerField(blank=True, default=1, verbose_name='单位面积可居住人数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate_type',
            name='number_of_work_person',
            field=models.IntegerField(blank=True, default=1, verbose_name='单位面积工作人数'),
            preserve_default=False,
        ),
    ]
