# Generated by Django 3.2.5 on 2021-11-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstateModel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCDE',
            fields=[
                ('abc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EstateModel.abc')),
                ('c', models.CharField(default='sbnt', max_length=20)),
            ],
            bases=('EstateModel.abc',),
        ),
    ]
