# Generated by Django 3.2.5 on 2021-10-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CityModel', '0005_auto_20211021_1535'),
        ('EstateModel', '0002_auto_20211021_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='location_county',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CityModel.county', verbose_name='位于县'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='location_suburb',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CityModel.suburb', verbose_name='位于郊区'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estate',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='建立于'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='fertility',
            field=models.FloatField(blank=True, default=0, verbose_name='肥力值'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='irrigation',
            field=models.FloatField(blank=True, default=0, verbose_name='灌溉值'),
        ),
        migrations.AlterField(
            model_name='estate_type',
            name='number_of_house_person',
            field=models.IntegerField(blank=True, default=0, verbose_name='单位面积可居住人数'),
        ),
        migrations.AlterField(
            model_name='estate_type',
            name='number_of_work_person',
            field=models.IntegerField(blank=True, default=0, verbose_name='单位面积工作人数'),
        ),
    ]
