# Generated by Django 3.2.5 on 2021-11-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstateModel', '0003_abcde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcd',
            name='abc_ptr',
        ),
        migrations.RemoveField(
            model_name='abcde',
            name='abc_ptr',
        ),
        migrations.DeleteModel(
            name='AB',
        ),
        migrations.DeleteModel(
            name='ABC',
        ),
        migrations.DeleteModel(
            name='ABCD',
        ),
        migrations.DeleteModel(
            name='ABCDE',
        ),
    ]
