# Generated by Django 3.2.5 on 2021-10-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EstateModel', '0003_auto_20211021_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estate_owner', to='auth.user', verbose_name='拥有者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='status_estate',
            field=models.CharField(choices=[('开垦中', '开垦中'), ('建设中', '建设中'), ('完成', '完成')], default='开垦中', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='estate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estate_user', to='auth.user', verbose_name='使用者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_county',
            field=models.BooleanField(verbose_name='位于县城？'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_suburb',
            field=models.BooleanField(verbose_name='位于郊区？'),
        ),
    ]
