# Generated by Django 3.2.5 on 2021-10-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CityModel', '0006_auto_20211022_2023'),
        ('CivitasModel', '0003_auto_20211021_1535'),
        ('EstateModel', '0004_auto_20211022_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_county',
            field=models.BooleanField(default=1, editable=False, verbose_name='是否位于县城'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='is_suburb',
            field=models.BooleanField(default=1, editable=False, verbose_name='是否位于郊区'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estate',
            name='fertility',
            field=models.FloatField(blank=True, null=True, verbose_name='肥力值'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='irrigation',
            field=models.FloatField(blank=True, null=True, verbose_name='灌溉值'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CityModel.county', verbose_name='位于县'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CityModel.suburb', verbose_name='位于郊区'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='now_lands',
            field=models.FloatField(editable=False, verbose_name='当前占地'),
        ),
        migrations.AlterField(
            model_name='estate_type',
            name='best_terrain',
            field=models.ManyToManyField(null=True, related_name='best_terrain', to='CivitasModel.Terrain', verbose_name='最适地形'),
        ),
        migrations.AlterField(
            model_name='estate_type',
            name='number_of_house_person',
            field=models.IntegerField(blank=True, null=True, verbose_name='单位面积可居住人数'),
        ),
        migrations.AlterField(
            model_name='estate_type',
            name='number_of_work_person',
            field=models.IntegerField(blank=True, null=True, verbose_name='单位面积工作人数'),
        ),
    ]
