# Generated by Django 3.2.5 on 2021-10-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CityModel', '0007_auto_20211022_2053'),
        ('CivitasModel', '0003_auto_20211021_1535'),
        ('EstateModel', '0005_auto_20211022_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='location_terrain',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='CivitasModel.terrain', verbose_name='位于某地形'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_county',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否位于县城'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_suburb',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否位于郊区'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CityModel.county', verbose_name='位于县'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_suburb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CityModel.suburb', verbose_name='位于郊区'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='now_lands',
            field=models.FloatField(default=0, editable=False, verbose_name='当前占地'),
        ),
        migrations.AlterField(
            model_name='estate_type',
            name='best_terrain',
            field=models.ManyToManyField(blank=True, related_name='best_terrain', to='CivitasModel.Terrain', verbose_name='最适地形'),
        ),
    ]
