# Generated by Django 3.2.5 on 2021-10-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0017_auto_20210813_2354'),
        ('CivitasModel', '0003_auto_20211021_1535'),
        ('EstateModel', '0006_auto_20211022_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='production_machining',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.recipe', verbose_name='产出配方'),
        ),
        migrations.AddField(
            model_name='estate',
            name='production_materials',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.materialdetail', verbose_name='产物'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='location_terrain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CivitasModel.terrain', verbose_name='位于某地形'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estate',
            name='now_lands',
            field=models.FloatField(default=0, verbose_name='当前占地'),
        ),
    ]
