# Generated by Django 3.2.5 on 2021-10-29 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DietModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_recipe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='diet_recipe',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DietModel.treatment_diet', verbose_name='烹饪方法'),
        ),
        migrations.AddField(
            model_name='diet_materialdetail',
            name='r_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DietModel.diet_material', verbose_name='食品'),
        ),
        migrations.AlterUniqueTogether(
            name='diet_materialdetail',
            unique_together={('r_material', 'level')},
        ),
    ]
