# Generated by Django 3.2.5 on 2021-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0002_diet_recipe_taste_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_recipe',
            name='taste_description',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
