# Generated by Django 3.2.5 on 2021-10-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_value_change', models.IntegerField()),
                ('type_of_behavior', models.CharField(choices=[('公开赞扬', '公开赞扬'), ('公开谴责', '公开谴责'), ('私下表扬', '私下表扬'), ('私下批评', '私下批评'), ('赠送礼物', '赠送礼物')], default='公开赞扬', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
