# Generated by Django 3.2.5 on 2021-11-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('title', models.CharField(max_length=40)),
                ('time', models.DateField()),
            ],
            options={
                'verbose_name': '开发日志',
                'verbose_name_plural': '开发日志',
            },
        ),
    ]
