# Generated by Django 3.2.5 on 2021-11-02 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Recipe_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '所需物资表',
                'verbose_name_plural': '所需物资表',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='物资id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='物资名')),
                ('type_of', models.CharField(choices=[('食品', '食品'), ('', 'Q2'), (3, 'Q3')], max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name': '物资',
                'verbose_name_plural': '物资',
            },
        ),
        migrations.CreateModel(
            name='Material_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity', models.FloatField(verbose_name='物资自身产能')),
                ('level', models.SmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')], default=1, verbose_name='物资等级')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material', verbose_name='物资')),
            ],
            options={
                'verbose_name': '物资详情',
                'verbose_name_plural': '物资详情',
                'unique_together': {('material', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Output_Recipe_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material_detail', verbose_name='物资')),
            ],
            options={
                'verbose_name': '产出物资表',
                'verbose_name_plural': '产出物资表',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ManyToManyField(related_name='recipe_input', through='MaterialModel.Input_Recipe_Material', to='MaterialModel.Material_Detail', verbose_name='输入')),
                ('output', models.ManyToManyField(related_name='recipe_output', through='MaterialModel.Output_Recipe_Material', to='MaterialModel.Material_Detail', verbose_name='输出')),
            ],
            options={
                'verbose_name': '配方',
                'verbose_name_plural': '配方',
            },
        ),
        migrations.AddField(
            model_name='output_recipe_material',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.recipe', verbose_name='配方'),
        ),
        migrations.AddField(
            model_name='input_recipe_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material_detail', verbose_name='输入物资'),
        ),
        migrations.AddField(
            model_name='input_recipe_material',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.recipe', verbose_name='配方'),
        ),
    ]
