# Generated by Django 3.2.5 on 2021-11-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='output_recipe_material',
            options={'verbose_name': '物资详情+数量表', 'verbose_name_plural': '物资详情+数量表'},
        ),
    ]
