# Generated by Django 3.2.5 on 2021-10-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivitasModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_day', models.IntegerField(verbose_name='总计日期')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('season', models.CharField(choices=[(1, '春'), (2, '夏'), (3, '秋'), (4, '冬')], default=1, max_length=20, verbose_name='季节')),
                ('day', models.IntegerField(verbose_name='当前日期')),
            ],
            options={
                'verbose_name': '日历',
                'verbose_name_plural': '日历',
            },
        ),
        migrations.DeleteModel(
            name='weather',
        ),
    ]
