# Generated by Django 3.2.5 on 2021-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivitasModel', '0002_auto_20211015_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='地形名')),
                ('default_open_difficulty', models.IntegerField(default=100, verbose_name='基准开垦难度')),
            ],
            options={
                'verbose_name': '地形',
                'verbose_name_plural': '地形',
            },
        ),
        migrations.AlterField(
            model_name='calendar',
            name='season',
            field=models.CharField(choices=[('1', '春'), ('2', '夏'), ('3', '秋'), ('4', '冬')], default='1', max_length=20, verbose_name='季节'),
        ),
    ]
