# Generated by Django 3.2.5 on 2021-11-02 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Skill',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='大类技能id')),
                ('name', models.CharField(max_length=20, verbose_name='大类技能名称')),
            ],
            options={
                'verbose_name': '大类技能',
                'verbose_name_plural': '大类技能',
            },
        ),
        migrations.CreateModel(
            name='Small_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.SmallIntegerField(verbose_name='大类下的小类id')),
                ('name', models.CharField(max_length=20, verbose_name='小类名称')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.big_skill', verbose_name='所属大类')),
            ],
            options={
                'verbose_name': '小类技能',
                'verbose_name_plural': '小类技能',
                'unique_together': {('sub', 'subid')},
            },
        ),
        migrations.CreateModel(
            name='User_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('type_of', models.CharField(choices=[('用户', '用户'), ('NPC', 'NPC')], default='用户', max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name': '用户技能',
                'verbose_name_plural': '用户技能',
            },
        ),
        migrations.CreateModel(
            name='User_Skill_To_Small_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_num', models.FloatField(default=0, verbose_name='技能点')),
                ('small_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.small_skill', verbose_name='小类技能')),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.user_skill', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户小类技能',
                'verbose_name_plural': '用户小类技能',
                'unique_together': {('user_skill', 'small_skill')},
            },
        ),
        migrations.CreateModel(
            name='User_Skill_To_Big_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_num', models.FloatField(default=0, verbose_name='技能点')),
                ('comprehension', models.FloatField(default=0, verbose_name='悟性')),
                ('level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='技能等级')),
                ('big_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.big_skill', verbose_name='大类技能')),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.user_skill', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户大类技能',
                'verbose_name_plural': '用户大类技能',
                'unique_together': {('user_skill', 'big_skill')},
            },
        ),
        migrations.AddField(
            model_name='user_skill',
            name='big_skill',
            field=models.ManyToManyField(related_name='big_skill', through='SkillModel.User_Skill_To_Big_Skill', to='SkillModel.Big_Skill', verbose_name='大类技能'),
        ),
        migrations.AddField(
            model_name='user_skill',
            name='small_skill',
            field=models.ManyToManyField(related_name='small_skill', through='SkillModel.User_Skill_To_Small_Skill', to='SkillModel.Small_Skill', verbose_name='小类技能'),
        ),
    ]
