# Generated by Django 3.2.5 on 2021-11-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_skill',
            options={'verbose_name': '技能表', 'verbose_name_plural': '技能表'},
        ),
    ]
