# Generated by Django 3.2.5 on 2021-11-02 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MaterialModel', '0001_initial'),
        ('SkillModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('原料产出', '原料产出'), ('加工', '加工'), ('随机产出', '随机产出'), ('服务', '服务')], default='原料产出', max_length=20, verbose_name='类型')),
                ('production_machining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.recipe', verbose_name='产出配方')),
                ('production_materials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_materials', to='MaterialModel.material_detail', verbose_name='产物')),
            ],
            options={
                'verbose_name': '工作类型',
                'verbose_name_plural': '工作类型',
            },
        ),
        migrations.CreateModel(
            name='Work_Main_To_Material_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(default=0, verbose_name='概率')),
                ('material_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material_detail', verbose_name='产出')),
                ('work_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkModel.work_main', verbose_name='工作类型')),
            ],
            options={
                'verbose_name': '随机产出中间表',
                'verbose_name_plural': '随机产出中间表',
            },
        ),
        migrations.AddField(
            model_name='work_main',
            name='production_random_materials',
            field=models.ManyToManyField(related_name='production_random_materials', through='WorkModel.Work_Main_To_Material_Detail', to='MaterialModel.Material_Detail', verbose_name='随机产出物资'),
        ),
        migrations.AddField(
            model_name='work_main',
            name='production_random_materials2',
            field=models.ManyToManyField(related_name='production_random_materials2', to='MaterialModel.Material_Detail', verbose_name='随机产出物资'),
        ),
        migrations.AddField(
            model_name='work_main',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.big_skill', verbose_name='大类技能'),
        ),
        migrations.AddField(
            model_name='work_main',
            name='skill_mini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillModel.small_skill', verbose_name='小类技能'),
        ),
    ]
